Improve configure script to fail with error message when needed header files could not be found.
git-svn-id: file:///home/svn/smcroute/trunk@49 9463870d-797f-4c04-96bf-d4a431643c59

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -3398,6 +3398,14 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
 #define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
 _ACEOF
 
+else
+  { { echo "$as_me:$LINENO: error: Could not find linux/mroute.h" >&5
+echo "$as_me: error: Could not find linux/mroute.h" >&2;}
+   { (exit 1); exit 1; }; }
+else
+  { { echo "$as_me:$LINENO: error: Could not find linux/mroute6.h" >&5
+echo "$as_me: error: Could not find linux/mroute6.h" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 done
@@ -3464,6 +3472,10 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
 #define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
 _ACEOF
 
+else
+  { { echo "$as_me:$LINENO: error: Could not find linux/mroute.h" >&5
+echo "$as_me: error: Could not find linux/mroute.h" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 done
@@ -3530,6 +3542,10 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
 #define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
 _ACEOF
 
+else
+  { { echo "$as_me:$LINENO: error: Could not find linux/mroute6.h" >&5
+echo "$as_me: error: Could not find linux/mroute6.h" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 done
